# WARNING: Do not edit this file.
# Add your deps in FindDeps/Public.cmake and FindDeps/Private.cmake
include(${PROJECT_SOURCE_DIR}/cmake/FindDeps/Public.cmake)
include(${PROJECT_SOURCE_DIR}/cmake/FindDeps/Private.cmake)